Update make.yml
Added logs and a bit of logic

diff --git a/.github/workflows/make.yml b/.github/workflows/make.yml
--- a/.github/workflows/make.yml
+++ b/.github/workflows/make.yml
@@ -22,14 +22,25 @@ jobs:
       run: make
     - name: run server
       run: |
-        ./ircserv 4242 password &
+        ./ircserv 4242 password > normal.log 2> error.log &
         echo $! > server_pid.txt
     - name: test connection
       run: |
-        nc localhost 4242
+        sleep 5
+        if nc -z localhost 4242; then
+          echo "Server is running"
+        else
+          echo "Server failed to start"
+          exit 1
+        fi
+    - name: show normal logs
+      run: cat normal.log
+    - name: show error logs
+      run: cat error.log
     - name: clean afterwards
+      if: success()
       run: |
-        kill -9 $( cat server_pid.txt )
+        kill -9 $( cat server_pid.txt ) || echo "Server already terminated"
 
   compile_in_MacOs:
     name: compile_Mac
@@ -42,12 +53,22 @@ jobs:
       run: make
     - name: run server
       run: |
-        ./ircserv 4242 password &
+        ./ircserv 4242 password > normal.log 2> error.log &
         echo $! > server_pid.txt
     - name: test connection
       run: |
-        nc localhost 4242
+        sleep 5
+        if nc -z localhost 4242; then
+          echo "Server is running"
+        else
+          echo "Server failed to start"
+          exit 1
+        fi
+    - name: show normal logs
+      run: cat normal.log
+    - name: show error logs
+      run: cat error.log
     - name: clean afterwards
+      if: success()
       run: |
-        kill -9 $( cat server_pid.txt )
-
+        kill -9 $( cat server_pid.txt ) || echo "Server already terminated"
